version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - webnet

networks:
  webnet:

volumes:
  postgres_data:
